name: CI - Lint, Format, Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run validation
        run: bun run ci
